chore: Switch discovery document updates from app engine cron to github action
googleapis/discovery-artifact-manager pull request #5338
Opened 2022-08-12 00:19 UTC by dazuma

Replaces #5305.

We're trying to turn down this repo's production services and delete as much of it as possible. Currently, the live parts of this repo are:

1. A cache for discovery documents (in the `/discoveries` directory) which is used by apiary generators for some languages
2. An App Engine cron and a GitHub Action auto-approver script that updates the discovery document cache hourly
3. Some code (in the `/src` and `/toolkit` directories) that is referenced from a google3 script that ACTools occasionally runs to manually update apiary samples

This PR is one step toward turning stuff down. It reimplements part (2) above in a bit of Python code that runs in an hourly scheduled GitHub Action. There are two python scripts: one that downloads the current discovery documents and updates the `/discoveries` directory, and another that opens a pull request, auto-approves it, and sets automerge.

This replaces the last live function of the App Engine app, which we can then turn down along with removing its attendant autoapprover script. (This PR just disables the associated App Engine crons; we will delete the entire `/server` directory in a subsequent PR. Also note that we are reimplementing the auto-approve functionality inside the python script rather than keeping it in a separate GitHub Action; this should make the system a bit more robust.)

2022-08-12 00:20 UTC, dazuma commented
@SurferJeffAtGoogle PTAL

2022-08-12 16:47 UTC, dazuma commented
Note: please review but do not submit. I need to coordinate submission with disabling the app engine app.

2022-08-18 18:38 UTC, SurferJeffAtGoogle requested changes

2022-08-18 18:38 UTC, SurferJeffAtGoogle commented on scripts/open_pr.py
> +        logging.info("Need to set git user.name.")
I first interpreted this log message to mean that I forget to set the user.name, and I need to set it.  Would you mind changing it to `f"Setting git user.name to {GIT_USER_NAME}."`

2022-08-18 18:38 UTC, SurferJeffAtGoogle commented on scripts/open_pr.py
> +        logging.info("Need to set git user.email.")
ditto

2022-08-18 18:38 UTC, SurferJeffAtGoogle commented on scripts/open_pr.py
> +    branch = commit_changes()
`commit_changes()` takes one argument.  I expect this line would raise an exception.

2022-08-18 18:38 UTC, SurferJeffAtGoogle commented on scripts/update_disco.py
> +        index_document {DocumentInfo} -- The index
With python3, we can use type annotations in the code.  Then, [mypy](https://github.com/python/mypy) can find lots of bugs before the code runs.

For Github automation tools, we run mypy and black on all our Python code.

2022-08-18 20:59 UTC, dazuma commented on scripts/open_pr.py
> +        logging.info("Need to set git user.name.")
Done

2022-08-18 20:59 UTC, dazuma commented on scripts/open_pr.py
> +        logging.info("Need to set git user.email.")
Done

2022-08-18 21:00 UTC, dazuma commented on scripts/open_pr.py
> +    branch = commit_changes()
Thanks, I failed to retest after doing a last refactor. Fixed.

2022-08-18 21:01 UTC, dazuma commented on scripts/update_disco.py
> +        index_document {DocumentInfo} -- The index
I went and added type annotations, ran both mypy and black, and retested end-to-end. Also added a CI workflow that runs mypy and black --check on these scripts.

2022-08-22 16:14 UTC, SurferJeffAtGoogle requested changes

2022-08-22 16:14 UTC, SurferJeffAtGoogle commented on scripts/update_disco.py
> +main()
Add an `if __name__ == '__main__'`: here.

Then, write tests that cover all the code in `update_disco.py` that doesn't make network calls.  That looks like all the code except the `main()` and `load_index()` functions.

2022-08-22 20:49 UTC, dazuma commented on scripts/update_disco.py
> +main()
Done

2022-08-22 21:01 UTC, SurferJeffAtGoogle approved these changes

2022-08-22 21:55 UTC, merged